version: '3.7'

services:
  # =kit
  kit:
    image: "sindriainc/devops-kit:${KIT_TAG}"
    #image: "<private-image>"
    container_name: "${APP_NAME}"
    command: tail -f /dev/null
    #user: sindria
    environment:
        - XDEV_SINDRIA_USER_PASSWORD=${XDEV_SINDRIA_USER_PASSWORD}
        - HOST_USER_UID=${HOST_USER_UID}
        - HOST_DOCKER_GROUP_UID=${HOST_DOCKER_GROUP_UID}
        - TZ=${TIMEZONE}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "projects:/home/sindria/Projects"
    hostname: "${APP_NAME}.local"
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    #networks:
    #  default:
    #    ipv4_address: "${KIT_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"

# =networks
#networks:
#  default:
#    name: "vpc_kit"
#    driver: bridge
#    ipam:
#      config:
#        - subnet: ${NETWORK_SUBNET}

# =volumes
volumes:
  projects: